name: CI
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Build C++
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j
          ls -la src
      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        - name: Install Rust
          run: |
            rustup update ${{ matrix.rust }} --no-self-update
            rustup default ${{ matrix.rust }}
      - name: Build Rust
        run: cargo build
