name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Build
       run: |
         mkdir build
         cd build
         cmake ..
         make -j
         ll src