name: Conditional run
on: [ push, pull_request ]

jobs:
  run_only_on_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Failing step
        run: unknown_command
      - name: Run if previous fails
        if: failure()
        run: echo "Running even if the previous step failed"
      - name: Failing step 2
        if: failure()
        run: unknown_command
      - name: Always run
        if: always()
        run: echo "Running always"
      - name: Failing step with continue-on-error
        continue-on-error: true
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Sleep for 2 minutes
        run: sleep 2m