name: Container per step
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Node version from job's docker
        run: node -v
      - name: Echo from step's docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /bin/echo
          args: Hello World!
      - name: Node version from step's docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
