name: Encrypted secret
on: push

jobs:
  decrypt_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Decrypt large secret
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE_GPG" --output decrypted_secret.json secret.json.gpg
        env:
          PASSPHRASE_GPG: ${{ secrets.PASSPHRASE_GPG }}
      - name: Print secret
        run: cat decrypted_secret.json