name: Clone with Action
on: push

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: List before
        run: |
          echo "ls -la"
          ls -la
      - name: Clone
        uses: actions/hello-world-javascript-action@v1
      - name: List after
        run: |
          echo "ls -la"
          ls -la
