name: Run scripts from repository
on: push

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "arg1 arg2"
