name: Slack notification
on: push

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send a Slack notification
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello!"